### PR TITLE
Fix welcome to jekyll post

### PR DESCRIPTION
**Pull request by Doimhneacht**
This change is [Reviewable](https://reviewable.io/reviews/gitlings/gitlings.github.io/10)

### CODE REVIEW

**Comment by mvlabat** [comment]
BTW, it's okay

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/gitlings/gitlings.github.io/10#-:-KPgJATEtJOoQNTWgXcB:b-kz0j6f)*

**Comment by mvlabat** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/gitlings/gitlings.github.io/10)*

**Comment by mvlabat** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/gitlings/gitlings.github.io/10#-KPgJoSE_cm8qS7YXD7F:-KPgJoSE_cm8qS7YXD7G:b-klfn21) (no related file):*
Oh, wait wait wait

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gitlings/gitlings.github.io/10)*

**Comment by Doimhneacht** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/gitlings/gitlings.github.io/10#-KPgJoSE_cm8qS7YXD7F:-KPgK4zeGHqmTXW05IxA:b-4q702h) (no related file):*
<details><summary><i>Previously, mvlabat (Vladyslav Batyrenko) wrote…</i></summary>
> Oh, wait wait wait
</details>
BTW, what?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gitlings/gitlings.github.io/10)*

**Comment by mvlabat** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/gitlings/gitlings.github.io/10#-KPgJoSE_cm8qS7YXD7F:-KPgKFx_m2-7Y_OLXQvg:b-43xvrk) (no related file):*
<details><summary><i>Previously, Doimhneacht (Hanna Rosul) wrote…</i></summary>
> BTW, what?
</details>
nothing its okei

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/gitlings/gitlings.github.io/10)*

**Pull request merged**
